export const FUNCTION_DICT = {
  RegionLTM: '工具6：长期基准分析 (指定区域)',
  PolarNHLTM: '工具6：长期基准分析 (北极)',
  PolarSHLTM: '工具6：长期基准分析 (南极)',
  RegionTrend: '工具7：趋势分析 (指定区域)',
  PolarNHTrend: '工具7：趋势分析 (北极)',
  PolarSHTrend: '工具7：趋势分析 (南极)',
  RegionEOF: '工具8：EOF分析 (指定区域)',
  PolarNHEOF: '工具8：EOF分析 (北极)',
  PolarSHEOF: '工具8：EOF分析 (南极)',
  AnnualTS: '工具9：时序分析 (年)',
  SeasonalTS: '工具9：时序分析 (季节)',
  SeasonalContourNH: '工具10：季节循环分析 (北极)',
  SeasonalContourSH: '工具10：季节循环分析 (南极)',
}
